import {cardimage1,
    cardimage2,
    vitamin,
    protein,
    bazal,
     } from '../../images'

const BlogCardData = [
    {
        header: " Kilo ve Yağ Kaybı",
        content: "Yağ kaybı, yağdan kilo kaybı anlamına gelir. Kilo vermekten daha spesifik ve sağlıklı bir hedeftir.",
        media: cardimage2,
        date: " 14.02.2022 ",
        button: "DEVAMINI OKU",
        modalheader: "Kilo Vermek ve Yağ Yakmak Arasındaki Fark Nedir? Kilo ve Yağ Kaybı",
        divider1: ".",
        modalcontentheader: "Kilo Kaybı Nedir?",
        modalcontenttext: "Kilo kaybı, genel vücut ağırlığınızdaki kas, su ve yağ kayıplarından kaynaklanan azalmayı ifade eder. Bununla birlikte, yağdan mı yoksa kastan mı kilo verdiğinizi bilmek zor olabilir.",
        divider2: ".",
        modalcontentheader2: "Yağdan Kilo Verdiğimizi Nasıl Anlarız?",
        modalcontenttext2 : "Bir tartı kullanarak kilo verme durumunuzu takip etmek yaygın bir uygulamadır. Tartı kullanımı kilonuzu öğrenmek için yardımcı olabilirken çoğu tartı, yağ kaybı ile kas kaybı arasında ayrım yapmaz. Bu nedenle, yalnızca tartı ile kilonuzu takip etmek, yağ mı yoksa kas mı kaybettiğinizi ve hangi miktarlarda kaybettiğinizi belirlemenin güvenilir bir yolu değildir. Vücut yağı da ölçen tartı, sahip olduğunuz yağ ve kas yüzdesini ölçerek vücut kompozisyonunuzun daha doğru bir resmini sağlayabilir. Vücut yağ yüzdenizi tahmin etmek için deri kıvrım kaliperleri de kullanabilirsiniz, ancak bu, doğruluğu sağlamak için pratik gerektirir."
    },
    {
        header: " SU&İNSAN ",
        content: "Su, oksijenden sonra insan yaşamında en önemli yere sahip olan maddedir.",
        media: cardimage1,
        date: " 14.02.2022 ",
        button: "DEVAMINI OKU",
        modalheader: "SU&İNSAN",
        divider1: ".",
        modalcontentheader: "İnsan Vücudu ve Su",
        modalcontenttext: "İnsan vücudunda bulunan kas dokuları, yağ dokularından daha fazla oranda su içermektedir. Vücudumuzda bulunan suyun, 2/3’ü hücrelerin içinde yer almakta, geri kalanı ise damarlarda, dokular arasında, sindirim sisteminde ve vücut boşluklarında bulunmaktadır.Hayati nitelikte pek çok fonksiyona sahip olan vücut sıvılarının (kan, mide salgısı, tükürük, gebelikte oluşan amniyotik sıvı, idrar) büyük kısmını su oluşturmaktadır.Su, besinler ve içecekler yoluyla vücuda alınmakta, alınan su sindirim sisteminde emildikten sonra kana karışmaktadır. Kan dolaşımı ile vücuda dağılan su, kılcal damarlardan çıkarak doku sıvısını oluşturmaktadır. Hücre içerisinde bazı kimyasal tepkimelere katılan su, tekrar hücre dışına çıkarak doku sıvısına dönüşmekte ve dokular yoluyla kan dolaşımına katılmaktadır. Kan dolaşımı aracılığıyla böbreklere gelen suyun büyük bir kısmı idrar olarak vücut dışına atılmaktadır. Bir kısmı ise, deri, solunum ve sindirim sistemi tarafından kullanılarak vücuttan atılmaktadır.Vücutta su tutulumu, vazopressin adı verilen hormon yoluyla sağlanmaktadır. Beyin, hipotalamusta sentezlenen vazopress hormonu ile, vücuttaki su tutulumunu düzenlemektedir. Vücutta suyun azaldığını ve susama hissini oluşturan algılayıcı ve uyarıcı hücreler de vücutta beyin kısmında bulunmaktadır.",
        divider2: ".",
        modalcontentheader2: "Günlük Su Tüketimi ve Vücut Dengesi",
        modalcontenttext2 : "Yetişkin bir insanın günlük su ihtiyacı yaklaşık olarak 2500 ml kadardır. Ancak bu miktar, sadece su olarak tüketilmesi gereken ihtiyacı oluşturmaktadır. Çay, kahve, meyve suyu gibi sıvı içeceklerin bazıları vücuttan su atılmasını arttırabileceği için, sadece su tüketiminin gerçekleştirilmesine dikkat edilmesi gerekmektedir. Vücutta, suyun vücuda alımı ve vücuttan atılması belli bir denge içinde gerçekleştirilmektedir. Temel olarak vücutta bulunan normal sıvı hacmi söz konusudur ve günlük olarak tüketilen suyun, vücuttaki sıvı hacmini koruması gerekmektedir. Vücutta bulunan sıvı hacminin korunması için, günlük sıvı alımının günlük sıvı kaybına eşit şekilde gerçekleşmesi gerekmektedir. Vücutta bulunan bu temel sıvı dengesinin bozulması durumunda ise, birtakım rahatsızlıklar ortaya çıkmaktadır. Vücut için yeterli miktarda ve nitelikte su tüketilmesi durumunda, vücudun ihtiyacı olan iz elementlerinin çoğu karşılanabilmektedir. Bu durum cildin güzelleşmesi ve bağışıklık sisteminin güçlenmesi olarak vücuda yansımaktadır. Yeterli ve nitelikli su tüketimi yoluyla; soğuk algınlığı, idrar yolu enfeksiyonları, böbrek taşları ve mesane kanseri oluşma riski düşmektedir. ",
        divider3: ".",
        modalcontentheader3: "Su Kaslarınıza Enerji Sağlar",
        modalcontenttext3: "Vücudumuzdaki tüm metabolik süreçlerin sorunsuz bir şekilde işlemesi için dengeli beslenmek ve yeterince su içmek gerekir. Kaslarımız için de durum farklı değildir; kasların optimal seviyelerde çalışması için enerji seviyesinin dengelenmesi önemlidir. Spor salonuna gitmeden ya da evinizde spor yapmadan önce su içtiğinizde suyun içerisindeki elektrolitler kaslarınızın enerji dengesini korur. Eğer su içmeyi ihmal ederseniz kaslarınız dehidrasyona uğrayabilir ve zayıflama döngüsüne girebilir. Bunun için antrenmanlardan önce mutlaka su içmeye özen göstermelisiniz. Böylelikle egzersiz yaparken daha yüksek bir performans sergileyebilir ve kaslarınızın büyüme sürecine girmesini kolaylaştırabilirsiniz.",
        divider4: ".",
        modalcontentheader4: "Su Ağrı Eşiğinizi Yükseltir",
        modalcontenttext4: "Antrenmanlar sırasında yaptığınız zorlu hareketler kaslarınızın ağrımasına neden olabilir. Minimal kas yırtılmalarının oluşması kaslanma sürecinde çok önemli olsa da hissedilen ağrı kimi zaman dayanılmaz hale gelebilir. Psikofizyoloji dergisinde yayımlanan bir araştırmanın sonucu yeterince su içen kişilerin ağrı eşiklerinin yükseldiğini ve dayanıklılıklarının arttığını göstermektedir. Gün içerisinde gerekenden az su içenlerde ağrı hissi daha fazla olur ve duyarlılık yükselir. Dolayısıyla antrenman yoğunluğunun ve süresinin azaltılması gerekir. Su içerek daha uzun ve zorlu antrenmanların üstesinden dahi kolayca gelebilirsiniz!",
        divider5: ".",
        modalcontentheader5: "Su Kaslarınızın Büyüme Sürecinde Görev Yapar",
        modalcontenttext5: "Hayalinizdeki kas yapısına ulaşmak için aylardır ve belki yıllardır çaba harcıyorsunuz. Yağsız kas kitlenizi arttırmak ve belirgin kaslara sahip olmak için yeri geldiğinde sosyal hayatınızdan yeri geldiğinde ise en sevdiğiniz yiyeceklerden uzak duruyorsunuz. Ama iş su içmeye gelince, maalesef birçok kişi gibi umursamazca bir tavır sergiliyorsunuz. Su içmek genel sağlığa sunduğu sayısız faydasının yanı sıra kas büyüme sürecini de hızlandırır. Su içtiğinizde egzersizler için enerji ihtiyacınızı karşılayabilirsiniz, üstelik kas büyümesini de arttırabilirsiniz. Journal of Strength and Conditioning dergisinde yayımlanan bir araştırma, susuz kalındığı zaman kasların boyut ve güç olarak gerilediğini ortaya koymaktadır. Su protein sentezi sürecinde de efektif bir rol oynadığından yeterince tüketilmediğinde kas yakımının başladığı bilinmektedir. ",
        divider6: ".",
        modalcontentheader6: "Su İçmek Kas Kramplarını Önler",
        modalcontenttext6: "Egzersiz yaparken ve hatta dinlenme anında aniden kramp ağrısıyla karşılaşmak oldukça zorlayıcı ve rahatsız edici olabiliyor. Su, sahip olduğu metabolik bileşenler sayesinde vücuttan zararlı maddelerin atılmasını sağlıyor. Su içmeyen kişilerde sıklıkla rastlanan kramp ağrıları antrenmanların yarıda kesilmesine de, kişinin ciddi düzeyde ağrı çekmesine de yol açabiliyor. Su içmenin kaslarınız ve vücudunuz için faydaları bunlarla da sınırlı değildir. Su aynı zamanda muhteşem bir iştah kesicidir. Yemeklerden önce su içildiğinde mide dolar ve aşırı yemek yeme dürtüsünü de yemekler için ayrılan alanı da azaltır. Sağlık otoriteleri yemeklerden önce su içen kişilerin her öğünde 75 kalori az aldıklarını ve bu rakamın yıla vurulduğunda 8-10 kiloya eş değer bir kalori olduğunu ortaya koymaktadır. Suyun bir diğer faydası da metabolizmayı hızlandırmasıdır. Özellikle bir miktar soğutulmuş su vücudu harekete geçirebilir. Vücut soğuk suyu ısıtmak için daha fazla çalışır ve su içerken kalori harcamaya başlar. Dengeli beslenen ve su içen kişiler egzersiz yaparak formlarına kavuşurken sağlıklarını da iyileştirebilirler.Sosyal izolasyonun önem kazandığı bugünlerde mümkün olduğunca dışarı çıkılmadığından evdeki tüm yiyeceklere kolay bir şekilde erişim sağlanabiliyor. İradesine hakim olanlarla olamayanlar arasındaki farkın açılacağı zamanlardayız ve su içmeyi maalesef tercih etmiyoruz. Daha sağlıklı olmak ve aynı zamanda kas gelişimimizi de desteklemek için günlük su tüketim miktarımızı arttırmamız gerekiyor. Suyu sevmiyorsanız içerisine limon, elma, kivi, tarçın gibi ilaveler yapabilir, doğal bir detoks sürecine de geçiş yapabilirsiniz.",

    },
    {
        header: " Bazal Metabolizma ",
        content: "İnsan vücudu yalnızca hareket halinde değil, dinlenme halinde de enerji, yani kalori harcar. Bunun sebebi, vücudun dinlenme halinde de temel yaşamsal işlevleri devam ettirmesidir...",
        media: bazal,
        date: " 14.02.2022 ",
        button: "DEVAMINI OKU",
        modalheader: "Bazal Metabolizma Nedir?",
        divider1: ".",
        modalcontenttext: "İnsan vücudu yalnızca hareket halinde değil, dinlenme halinde de enerji, yani kalori harcar. Bunun sebebi, vücudun dinlenme halinde de temel yaşamsal işlevleri devam ettirmesidir. Bunlar nefes alıp verme, kan dolaşımı, sindirim, beyin ve sinir sistemi fonksiyonları ve hücre üretimidir. Bazal metabolizma, söz konusu temel işlevlerin devamı için enerji sağlayan metabolizmadır.",
        divider2: ".",
        modalcontentheader2: "Bazal Metabolizma Hızı (BMH) Nedir?",
        modalcontenttext2 : "Bazal metabolizma hızı, kişinin vücudunun temel yaşamsal fonksiyonları yerine getirmek için ihtiyaç duyduğu minimum kalori miktarına karşılık gelir ve kişiden kişiye farklılık gösterir. Bazal metabolizma ve dinlenme metabolizması sıklıkla karıştırılmaktadır. Dinlenme metabolizma hızı hesaplanırken vücudun yaşamsal fonksiyonlar dışında dinlenme halindeyken harcadığı kalorilerin de hesaba katılması gerekmektedir. Ancak her iki durumda da vücudun başka herhangi bir aktivite yapmıyor iken harcadığı enerji/kalori miktarı söz konusudur.Bazal metabolizma hızı genellikle yaşla birlikte vücuttaki yağsız vücut kütlesinin azalması sebebiyle düşer. Ortalama olarak kişilerin günlük kalori ihtiyacının %60-75’ini bazal metabolizma oluşturur. 20’li yaşlardan itibaren bazal metabolizma hızı her on yılda bir %1-2 oranında azalır. Ancak kişilerin genetik yapısı, aktivite miktarı ve beslenme biçimlerine göre bazal metabolizma hızında farklılıklar görülebilir.",
        divider3: ".",
        modalcontentheader3: "Bazal Metabolizma Hızını Belirleyen Etmenler Nelerdir?",
        modalcontenttext3: "Bazal metabolizma hızı kişiler arasında büyük farklılıklar gösterir. Ortalama olarak 1000 ile 2500 kalori arasında değişebilir. Bazal metabolizma hızını belirleyen en önemli etmen, kişinin yağsız vücut kütlesidir. Yağsız vücut kütlesi vücut kompozisyonun bir parçasıdır. Vücut dokularının depoladığı yağ dışında kalan hücre içi ve hücre dışı sıvılarını, kas dokusunu ve mineralleri içerir. Vücuttaki yağ kütlesinin toplam vücut ağırlığından çıkarılması yoluyla hesaplanır. Yağsız vücut kütlesinin hesaplanması için de kadın ve erkek için farklı formüller kullanılır.Yağsız vücut kütlesi dışında kişilerin yaşı, günlük aktivite miktarı ve aktivite biçimi; vücuda alınan besinler, cinsiyet, hormonal durumlar, genetik yapı ve kadınlar için menopoz bazal metabolizma hızını belirleyici diğer faktörlerdir. Ayrıca çeşitli metabolik hastalıklar, stres, uzun süren düşük kalorili diyetler de bazal metabolizma hızını etkiler.",
        divider4: ".",
        modalcontentheader4: "Bazal Metabolizma Hızı Değişir mi?",
        modalcontenttext4: "Bazal metabolizma hızı sabit bir değer değildir. Kişilerin yağsız vücut kütlesini artıracak egzersizler yapması, hormonal bozuklukların giderilmesi, doğru beslenme, düzenli uyku gibi desteklerle bazal metabolizma hızı artırılabilir. Günlük sıvı tüketimine dikkat edilmesi ve beden kitle endeksine göre kişinin alması gereken su miktarının altına düşmemesi de bazal metabolizmanın yavaşlamaması için önemlidir.",
        divider5: ".",
        modalcontentheader5: "Bazal Metabolizma Hızını Bilmek Neden Gereklidir?",
        modalcontenttext5: "Bazal metabolizma hızı değeri; kişilerin kilo alma, kilo verme ya da mevcut kilolarını koruma gibi durumlarda günlük ortalama ne kadar kalori almaları gerektiğini hesaplamak için kullanılır. Her ne kadar kilo alıp verme süreçlerinde belirleyici tek faktör alınan kalori miktarı olmasa da BMH hesapları kişilere ortalama değerler hakkında fikir verir.Günlük alınması gereken kalori miktarı kişiden kişiye farklılık gösterir ve birden fazla etmene göre belirlenir. Bazal metabolizma hızı bu etmenlerden yalnızca biridir. Buna cinsiyet ve günlük aktivite miktarı da eklenerek kişilerin ortalama günlük kalori ihtiyacı belirlenir. Aktivite seviyeleri genel olarak sedanter (hareketsiz), hafif aktivite, orta seviye aktivite, yüksek aktivite, çok yüksek aktivite olarak sınıflandırılır. Bu aktivite sınıflandırmalarına göre BMH hesaplarında kullanılan değişkenler de farklılık gösterir.",       

    },
    {
        header: "Vitamin ",
        content: "Vitamin, bir canlının metabolizmasının düzgün çalışması için küçük miktarlarda ihtiyaç duyduğu temel bir mikro besin olan organik bir moleküldür",
        media: vitamin,
        date: " 14.02.2022 ",
        button: "DEVAMINI OKU",
        modalheader: "Vitamin",
        divider1: ".",
        modalcontenttext: "Vitamin, bir canlının metabolizmasının düzgün çalışması için küçük miktarlarda ihtiyaç duyduğu temel bir mikro besin olan organik bir moleküldür (veya kimyasal olarak yakından ilişkili bir molekül grubudur, yani vitamerlerdir). Esansiyel besinler canlıda ya hiç sentezlenemez ya da yeterli miktarlarda sentezlenemez ve bu nedenle beslenme yoluyla alınması gerekir. C vitamini bazı türler tarafından sentezlenebilirken diğerleri tarafından sentezlenemez; ilk etapta bir vitamin değildir, ikinci sıradadır. Vitamin terimi diğer üç temel besin grubunu içermez: mineraller, esansiyel yağ asitleri ve esansiyel amino asitler Çoğu vitamin tek bir molekül değil, vitaminler adı verilen ilgili molekül gruplarıdır. Örneğin, sekiz E vitamini vardır: dört tokoferol ve dört tokotrienol. Bazı kaynaklar kolin de dahil olmak üzere on dört vitamini listeler,[2] ancak büyük sağlık kuruluşları on üç vitamini listeler: A vitamini (tüm trans-retinol, tüm-trans-retinil-esterler, ayrıca tüm-trans-beta-karoten ve diğer provitamin A karotenoidleri olarak), B1 vitamini (tiamin), B2 vitamini (riboflavin), B3 vitamini (niasin), B5 vitamini (pantotenik asit), B6 ​​vitamini (piridoksin), B7 vitamini (biyotin), B9 vitamini (folik asit veya folat), B12 vitamini (kobalaminler), C vitamini (askorbik asit), D vitamini (kalsiferoller), E vitamini (tokoferoller ve tokotrienoller) ve K vitamini (filokinon ve menakinonlar).Tüm vitaminler 1913 ile 1948 arasında keşfedildi (tanımlandı). Tarihsel olarak, beslenmeden vitamin alımı eksik olduğunda, sonuçlar vitamin eksikliği hastalıklarıydı. Daha sonra, 1935'ten başlayarak, ticari olarak üretilen maya özü B vitamini kompleksi ve yarı sentetik C vitamini tabletleri piyasaya çıktı. Bunu 1950'lerde, genel popülasyondaki vitamin eksikliklerini önlemek için multivitaminler de dahil olmak üzere vitamin takviyelerinin seri üretimi ve pazarlanması izledi. Hükümetler, eksiklikleri önlemek için gıda takviyesi olarak adlandırılan un veya süt gibi temel gıdalara bazı vitaminlerin eklenmesini zorunlu kılmıştır. Hamilelik sırasında folik asit takviyesi önerileri, bebek nöral tüp defekti riskini azaltmıştır. "

    },
    {
        header: "Protein Tozu ",
        content: "Protein tozu, peynir üretimi sırasında meydana gelen peynir altı suyunun çeşitli filtreleme yöntemleri kullanarak toz haline getirilmesiyle ortaya çıkan üründür.",
        media: protein,
        date: " 14.02.2022 ",
        button: "DEVAMINI OKU",
        modalheader: " Protein Tozu Nedir?",
        divider1: ".",
        modalcontenttext:"Protein tozu, peynir üretimi sırasında meydana gelen peynir altı suyunun çeşitli filtreleme yöntemleri kullanarak toz haline getirilmesiyle ortaya çıkan üründür. Bu filtreleme sırasında peynir altı suyu, sahip olduğu yüksek yağ, şeker ve tuzdan arındırılır ve proteince zenginleştirilerek piyasaya “peynir altı suyu tozu” yani ‘whey proteini’ olarak piyasaya sunulur.Protein tozları, whey ve kazein olarak 2 farklı şekilde karşımıza çıkmaktadır. Kazein, sütte %80 oranında bulunan bir bileşendir. Whey proteininden farklı olarak vücut tarafından sindirimi ve emilimi daha yavaş gerçekleşir.",
        modalcontentheader2:"Protein Tozu Nasıl Kullanılır?",
        divider2: ".",
        modalcontenttext2 :"Protein tozu ürünleri, hızlı emilime sahiptirler. Bu nedenle antrenman sonrası kullanımları en ideal olanıdır. Ek olarak, gün içinde herhangi bir zaman diliminde de protein açığını kapatmak amacıyla whey proteini ya da kazein proteini kullanılabilir. Bunun dışında kazein yerine whey protein kullanıyor ve yine sindirimini yavaşlatmak istiyorsanız, biraz kuruyemiş (fındık, yer fıstığı, ceviz gibi) ile birlikte tüketebilirsiniz. Kuruyemişlerin içerdiklerii yağ asitleri, whey proteinin emilimini yavaşlatacak ve insülin seviyesinin dengede kalmasına yardımcı olacaktır.",
        divider3: ".",
        modalcontentheader3:"Merdiven Altı Protein Tozlarına Dikkat",
        modalcontenttext3:"Günümüzde spora ve özellikle fitness ve vücut geliştirme sporuna talebin artmasıyla, protein tozuna olan talebi de arttırdı. Piyasada ismi cinsi belli olmayan bir sürü marka çıktı. İçeriğine ve markasına güvenmediğiniz ürünleri ucuz diye kullanmayın. Yoksa nesquikle aynı verimi alabilirsiniz.",
        divider4: ".",
        modalcontentheader4:"Günlük Protein İhtiyacı Ne Kadardır?",
        modalcontenttext4:"DRI (Diyette Referans Alım Miktarı), günlük alınması gereken protein miktarını vücut ağırlığının kilogramı başına 0,8 gram olarak belirtmektedir. Bu miktar: Hareketsiz (sedanter) bir erkek için günde ortalama 56 gram, Hareketsiz (sedanter) bir kadın için günde ortalama 46 gramdır. Bu kısıtlı miktar, genel olarak protein eksikliğini önlemek için yeterlidir. Fakat bazı çalışmalar, optimal sağlık ve vücut kompozisyonunu korumak için bu miktarın yeterli olmadığını göstermektedir. Herhangi bir birey için doğru miktarda proteinin, aktivite düzeyi, yaşı, kas kütlesi, fiziksel hedefleri ve mevcut sağlık durumu gibi birçok faktöre bağlı olduğu bilinmektedir. Eğer işiniz fiziksel olarak sizi zorluyorsa, çok yürüyorsanız, koşuyorsanız, yüzüyorsanız ya da herhangi bir egzersiz yapıyorsanız daha fazla günlük protein almanız gerekmektedir. Örneğin; dayanıklılık sporcuları önemli miktarda proteine ihtiyaç duyarlar. Bu sporcular kilo başına yaklaşık 1,2-1,4 gram protein almak zorundadır. Protein bakımından zengin bir diyet uygulayan sporcular, aynı zamanda protein tozu takviyeleri kullanarak bu ihtiyaçlarını daha düzenli ve kontrollü şekilde karşılayabilirler. Kütle kazanımında önemli rol oynayan amino asit gibi bileşenler de içeren protein tozu ürünleri, dayanıklılığın yanı sıra kas toparlanmasına ve güç kazanımına da katkıda bulunur. Öte yandan yaşlı bireylerin protein ihtiyacı da önemli ölçüde artmaktadır. Bu kitlenin DRI'ın (Diyette Referans Alım Miktarı: 46 gram) % 50 fazlası ya da kilo başına 1–1,3 gram protein tüketmesi gerekmektedir. Bu miktar, yaşlılarda osteoporoz ve sarkopeni (kas kütlesinde azalma) problemini önlemeye yardımcı olabilir. Ayrıca herhangi bir yaralanma ya da sakatlanma durumu geçiren kişiler de daha fazla protein ihtiyaç duyabilirler.",

    },
 
];

export default  BlogCardData;